name: Deploy

on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    environment: staging
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - name: Install wrangler
        run: npm install -g wrangler@2.4.0
      - name: Initializing .env for wrangler
        run: |
          touch .env
          echo "CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN" > .env
          echo "CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID" > .env
      - name: Putting secrets to cloudflare
        run: echo "$BOT_TOKEN" | wrangler secrets put BOT_TOKEN
      - name: Publishing to Cloudflare
        run: wrangler publish | tee wrangler_output.txt
      - name: Updating Telegram webhook
        run: |
          url=$(cat wrangler_output.txt | grep -o "https://.*")
          curl -X POST -H "Content-Type: application/json" --data-raw '{ \
            "url": "$url" \
          }' https://api.telegram.org/bot$BOT_TOKEN/setWebhook