name: Deploy

on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    environment: staging
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node@18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install wrangler
        run: |
          set -xeuo pipefail
          npm install -g wrangler@2.4.0
      - name: Initializing .env for wrangler
        run: |
          set -xeuo pipefail
          touch .env
          echo "CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN" > .env
          echo "CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID" > .env
      - name: Putting secrets to cloudflare
        run: |
          set -xeuo pipefail
          echo "$BOT_TOKEN" | wrangler secret put BOT_TOKEN
      - name: Publishing to Cloudflare
        run: |
          set -xeuo pipefail
          wrangler publish | tee wrangler_output.txt
      - name: Updating Telegram webhook
        run: |
          set -xeuo pipefail
          url=$(cat wrangler_output.txt | grep -o "https://.*")
          curl -X POST -H "Content-Type: application/json" --data-raw '{ "url": "'"$url"'" }' https://api.telegram.org/bot$BOT_TOKEN/setWebhook